# Generated by Django 5.0.8 on 2024-09-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
